global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "targets.rules"
  - "hosts.rules"
  - "containers.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'Containers'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']
      - targets: ['172.17.0.2:9100']
        labels:
         alias: 'Web'
      - targets: ['172.17.0.3:9100']
        labels:
         alias: 'Correo'
      - targets: ['172.17.0.4:9100']
        labels:
         alias: 'Mysql'


  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']


# sample scrape configuration for AWS EC2
  - job_name: 'nodeexporter'
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
    relabel_configs:
        # Only monitor instances which have a tag called Monitoring "Monitoring"
      - source_labels: [__meta_ec2_tag_Monitoring]
        regex: On
        action: keep

  - job_name: 'cadvisor'
    ec2_sd_configs:
      - region: us-east-1
        port: 9010
    relabel_configs:
        # Only monitor instances which have a tag called Monitoring "Monitoring"
      - source_labels: [__meta_ec2_tag_Monitoring]
        regex: On
        action: keep
